import './styles.css';
import { lessons, roadmap } from './lessons.js';

const STORAGE_KEY = 'english-with-yuri-v1';
const blankState = { completed: [], currentLesson: 1, currentStep: 0, minutes: 15, xp: 0, mistakes: [], learnedWords: [], skill: { ฟัง: 0, พูด: 0, อ่าน: 0, เขียน: 0 }, showThaiSound: false, assessment: null };
const load = () => { try { return { ...structuredClone(blankState), ...JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}') }; } catch { return structuredClone(blankState); } };
let state = load();
let page = location.hash.slice(1) || 'today';
let lessonSession = { selected: {}, arranged: [], showTranscript: false, recording: false, recognitionText: '', audioUrl: null };
const save = () => localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
const esc = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const app = document.querySelector('#app');
const icons = { today:'⌂', lessons:'▤', practice:'◎', vocab:'◇', progress:'↗' };
const labels = { today:'วันนี้', lessons:'บทเรียน', practice:'ฝึกทักษะ', vocab:'คำศัพท์', progress:'ความก้าวหน้า' };

function shell(content) {
  const nav = Object.keys(labels).map(key => `<button class="nav-btn ${page===key?'active':''}" data-nav="${key}">${labels[key]}</button>`).join('');
  const mobile = Object.keys(labels).map(key => `<button class="${page===key?'active':''}" data-nav="${key}" aria-label="${labels[key]}"><span class="nav-icon">${icons[key]}</span>${labels[key]}</button>`).join('');
  app.innerHTML = `<div class="app"><header class="topbar"><button class="brand" data-nav="today" aria-label="กลับหน้าแรก"><span class="logo"><span>Y</span></span>English with Yuri</button><nav class="desktop-nav" aria-label="เมนูหลัก">${nav}</nav><button class="profile-btn" data-nav="progress" aria-label="ดูความก้าวหน้า">ยู</button></header><main class="main">${content}</main><nav class="bottom-nav" aria-label="เมนูหลักบนมือถือ">${mobile}</nav></div>`;
  bindCommon();
}

function bindCommon(){
  document.querySelectorAll('[data-nav]').forEach(b => b.onclick = () => navigate(b.dataset.nav));
  document.querySelectorAll('[data-lesson]').forEach(b => b.onclick = () => startLesson(+b.dataset.lesson));
  document.querySelectorAll('[data-speak]').forEach(b => b.onclick = () => speak(b.dataset.speak));
}
function navigate(next){ page=next; location.hash=next; render(); scrollTo(0,0); }
function speak(text, rate=1){ if(!('speechSynthesis' in window)) return toast('อุปกรณ์นี้ไม่รองรับเสียงสังเคราะห์'); speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.lang='en-US';u.rate=rate;speechSynthesis.speak(u); }
function toast(text){ const old=document.querySelector('.toast'); if(old)old.remove(); const el=document.createElement('div');el.className='toast';el.textContent=text;document.body.append(el);setTimeout(()=>el.remove(),2400); }

function render(){
  if(page.startsWith('learn-')) return renderLesson(+page.split('-')[1]);
  const views={today:renderToday,lessons:renderLessons,practice:renderPractice,vocab:renderVocab,progress:renderProgress,assessment:renderAssessment};
  (views[page]||renderToday)();
}

function renderToday(){
  const current=lessons.find(l=>l.id===state.currentLesson)||lessons[0]; const pct=Math.round(state.currentStep/7*100);
  shell(`<section class="hero"><div><p class="eyebrow">ภาษาอังกฤษ เริ่มทีละนิด</p><h1>เริ่มจาก <em>“ไม่รู้”</em><br>ไปสู่ “พูดได้จริง”</h1><p class="hero-copy">ไม่ต้องเก่ง ไม่ต้องรีบ ยูริจะพาเรียนทีละขั้นด้วยคำอธิบายภาษาไทยง่าย ๆ วันละนิดก็เก่งขึ้นได้</p><div class="actions"><button class="btn primary" data-lesson="${current.id}">▶ ${state.currentStep?'เรียนต่อจากจุดเดิม':'เริ่มจากศูนย์'}</button><button class="btn secondary" id="assessment">ทำแบบประเมิน (ทางเลือก)</button></div></div><div class="hero-art" aria-hidden="true"><div class="teacher"><div class="speech">Hello! พร้อมเริ่มไหมคะ?</div><div class="teacher-face">👩🏻‍🏫</div></div></div></section>
  <div class="section-title"><div><h2>บทเรียนวันนี้</h2><p>ค่อย ๆ เรียนในจังหวะของคุณ</p></div></div><section class="today-grid"><article class="card lesson-feature"><div class="big-icon">${current.icon}</div><div><div class="feature-meta"><span class="pill">บทที่ ${current.id}</span><span>⏱ ${current.minutes} นาที</span></div><h3>${current.title}</h3><p>${current.subtitle}</p></div><div class="feature-bottom"><div class="bar"><i style="width:${pct}%"></i></div><span>${pct}%</span><button class="btn primary" data-lesson="${current.id}">${pct?'เรียนต่อ':'เริ่มเรียน'} →</button></div></article><article class="card time-card"><h3>วันนี้อยากเรียนกี่นาที?</h3><p>เลือกให้พอดีกับวันของคุณ เปลี่ยนได้เสมอ</p><div class="segmented">${[15,30,60].map(n=>`<button data-time="${n}" class="${state.minutes===n?'active':''}">${n} นาที</button>`).join('')}</div><div class="tip-box">🌱 เรียนสม่ำเสมอแบบไม่กดดัน สำคัญกว่าการเรียนรวดเดียวเยอะ ๆ นะ</div></article></section>
  <div class="skill-row">${Object.entries(state.skill).map(([k,v])=>`<article class="card skill"><div class="skill-head"><strong>${{ฟัง:'🎧',พูด:'🎙️',อ่าน:'📖',เขียน:'✏️'}[k]} ${k}</strong><span>${v}%</span></div><div class="bar"><i style="width:${v}%"></i></div></article>`).join('')}</div>
  <div class="section-title"><div><h2>แผน 12 สัปดาห์</h2><p>ไม่มีคำสัญญาว่าจะคล่องในเวลาตายตัว แต่ทุกบทจะพาคุณเข้าใกล้เป้าหมาย</p></div></div><div class="roadmap">${roadmap.map(r=>`<article class="card road-card ${r[3]}"><span class="muted-label">${r[0]}</span><h3>${r[1]}</h3><p>${r[2]}</p><span class="pill">${r[3]==='ready'?'มีบทเรียนแล้ว':'กำลังเตรียมบทเรียน'}</span></article>`).join('')}</div>`);
  document.querySelector('#assessment').onclick=()=>navigate('assessment');
  document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{state.minutes=+b.dataset.time;save();renderToday();});
}

function renderLessons(){
  shell(`<header class="page-head"><p class="eyebrow">เส้นทางของคุณ</p><h1>บทเรียนทั้งหมด</h1><p>10 บทแรกพร้อมเรียนแล้ว เริ่มจากบทแรกหรือกลับมาต่อได้ทุกเมื่อ</p></header><div class="lesson-grid">${lessons.map(l=>`<button class="card lesson-card" data-lesson="${l.id}" aria-label="เริ่มบทที่ ${l.id} ${l.title}"><span class="lesson-icon">${l.icon}</span><span><span class="muted-label">บทที่ ${l.id} · ${l.minutes} นาที</span><h3>${l.title}</h3><p>${l.subtitle}</p></span><span class="circle-status ${state.completed.includes(l.id)?'done':''}">${state.completed.includes(l.id)?'✓':'→'}</span></button>`).join('')}</div><div class="section-title"><div><h2>บทต่อไป</h2><p>หัวข้อที่กำลังจัดทำ—ยังไม่เปิดให้เรียน</p></div></div><div class="roadmap"><article class="card road-card soon"><span class="muted-label">บทที่ 11 · ยังไม่พร้อม</span><h3>ซื้อของและถามราคา</h3><p>ฝึกสนทนาในร้านค้าอย่างสุภาพ</p></article><article class="card road-card soon"><span class="muted-label">บทที่ 12 · ยังไม่พร้อม</span><h3>เดินทางในเมือง</h3><p>ถามทางและใช้ขนส่งสาธารณะ</p></article></div>`);
}

function renderPractice(){
 const pending=state.mistakes.length; shell(`<header class="page-head"><p class="eyebrow">ฝึกให้มั่นใจ</p><h1>ทบทวนวันนี้</h1><p>เรานำข้อที่พลาดกลับมาให้ลองใหม่ โดยไม่ตัดสินและไม่เร่งคุณ</p></header><div class="today-grid"><article class="card lesson-feature"><div class="big-icon">🧠</div><div><span class="pill">เหมาะกับคุณ</span><h3>${pending?`${pending} ข้อที่ควรลองอีกครั้ง`:'ยังไม่มีข้อที่ต้องทบทวน'}</h3><p>${pending?'ลองใหม่ได้เลย ความผิดพลาดคือส่วนหนึ่งของการเรียน':'เริ่มทำบทเรียน แล้วแบบฝึกที่ยังไม่แม่นจะมาอยู่ที่นี่'}</p></div><div class="feature-bottom"><button class="btn primary" ${pending?'':'disabled'} id="reviewMistakes">เริ่มทบทวน</button></div></article><article class="card time-card"><h3>ฝึกออกเสียงอิสระ</h3><p>ฟังต้นแบบ แล้วพูดตามในบทเรียนแต่ละบทได้ ระบบจะไม่ใช้ข้อความที่ได้ยินเป็นคะแนนการออกเสียง</p><button class="btn secondary" data-lesson="${state.currentLesson}">ไปฝึกพูด →</button></article></div><div class="section-title"><div><h2>เลือกทักษะ</h2></div></div><div class="skill-row">${['ฟัง','พูด','อ่าน','เขียน'].map((x,i)=>`<button class="card skill" data-lesson="${state.currentLesson}"><div class="big-icon" style="width:48px;height:48px;font-size:23px">${['🎧','🎙️','📖','✏️'][i]}</div><h3>ฝึก${x}</h3><span>รวมอยู่ในบทเรียน</span></button>`).join('')}</div>`);
 const review=document.querySelector('#reviewMistakes'); if(review)review.onclick=()=>{ const m=state.mistakes[0];if(m)startLesson(m.lesson);};
}

function renderVocab(){
 const words=state.learnedWords.length?state.learnedWords:[];
 shell(`<header class="page-head"><p class="eyebrow">คลังคำของคุณ</p><h1>คำศัพท์ของฉัน</h1><p>คำที่พบในบทเรียนจะถูกเก็บไว้ให้กลับมาฟังและทบทวน</p></header><div class="vocab-page-grid"><section class="card vocab-table">${words.length?words.map(w=>`<div class="vocab-item"><div><strong class="word-en">${esc(w[0])}</strong><span class="word-th">${esc(w[1])}</span></div><span class="thai-sound">${esc(w[2])}</span><button class="sound-btn" data-speak="${esc(w[0])}" aria-label="ฟังคำว่า ${esc(w[0])}">▶</button></div>`).join(''):`<div class="empty"><div class="emoji">📚</div><h3>ยังไม่มีคำศัพท์</h3><p>คำใหม่จะมาอยู่ที่นี่เมื่อคุณเริ่มเรียนบทแรก</p><button class="btn primary" data-lesson="1">เริ่มบทแรก</button></div>`}</section><aside class="card side-card"><h3>เกี่ยวกับคำอ่านไทย</h3><p>คำอ่านเป็นเพียงเสียงโดยประมาณ เสียงภาษาอังกฤษจากปุ่มฟังคือต้นแบบหลัก</p><label class="toggle"><input type="checkbox" id="thaiToggle" ${state.showThaiSound?'checked':''}> แสดงคำอ่านไทยในบทเรียน</label></aside></div>`);
 document.querySelector('#thaiToggle').onchange=e=>{state.showThaiSound=e.target.checked;save();toast(e.target.checked?'เปิดคำอ่านไทยแล้ว':'ปิดคำอ่านไทยแล้ว');};
}

function renderProgress(){
 const done=state.completed.length; const learned=state.learnedWords.length;
 shell(`<header class="page-head"><p class="eyebrow">เติบโตในจังหวะของคุณ</p><h1>ความก้าวหน้า</h1><p>คำนวณจากแบบฝึกที่ทำจริง ไม่ใช่คะแนนหรือผลวิเคราะห์ที่สร้างขึ้น</p></header><div class="stats-grid"><article class="card stat"><div class="num">${done}/10</div><p>บทที่เรียนจบ</p></article><article class="card stat"><div class="num">${learned}</div><p>คำศัพท์ที่พบแล้ว</p></article><article class="card stat"><div class="num">${state.xp}</div><p>กิจกรรมที่ทำสำเร็จ</p></article></div><div class="today-grid"><section class="card side-card"><h2>แต่ละทักษะ</h2>${Object.entries(state.skill).map(([k,v])=>`<div class="skill"><div class="skill-head"><strong>${k}</strong><span>${v}%</span></div><div class="bar"><i style="width:${v}%"></i></div></div>`).join('')}</section><aside class="card side-card"><h2>ข้อมูลของฉัน</h2><p>เวอร์ชันนี้เก็บข้อมูลในอุปกรณ์นี้ด้วย localStorage และยังไม่ซิงก์ข้ามเครื่อง</p><div class="settings-block"><button class="btn secondary" id="export">ส่งออกข้อมูล</button><label class="btn secondary" for="import">นำเข้าข้อมูล</label><input hidden type="file" id="import" accept="application/json"><button class="btn danger" id="reset">รีเซ็ตข้อมูล</button></div></aside></div>`);
 document.querySelector('#export').onclick=exportData;document.querySelector('#import').onchange=importData;document.querySelector('#reset').onclick=resetData;
}

function renderAssessment(){
 shell(`<section class="assessment"><button class="back" data-nav="today">← กลับหน้าแรก</button><div class="card assessment-step"><p class="eyebrow">แบบประเมินทางเลือก</p><h1>ลองตอบ 3 ข้อสั้น ๆ</h1><p class="step-lead">ไม่มีผลต่อการเริ่มเรียน ใช้เพื่อแนะนำจุดเริ่มต้นเท่านั้น</p><div class="question">“I am happy.” หมายถึงอะไร?</div><div class="options" data-assess="1"><button class="option">ฉันมีความสุข</button><button class="option">ฉันหิว</button></div><div class="question">เลือกคำที่เติม: We ___ friends.</div><div class="options" data-assess="2"><button class="option">are</button><button class="option">am</button></div><div class="question">“Where” ใช้ถามเรื่องใด?</div><div class="options" data-assess="3"><button class="option">สถานที่</button><button class="option">เวลา</button></div><div class="step-actions"><span></span><button class="btn primary" id="finishAssess">ดูคำแนะนำ</button></div></div></section>`);
 document.querySelectorAll('[data-assess] .option').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');});
 document.querySelector('#finishAssess').onclick=()=>{const answers=[...document.querySelectorAll('[data-assess]')].map(x=>x.querySelector('.selected')===x.firstElementChild);const score=answers.filter(Boolean).length;state.assessment=score;save();toast(score>=2?'พื้นฐานดีเลย แนะนำเริ่มบท 2':'เริ่มบท 1 ได้เลย ยูริจะพาไปทีละขั้น');setTimeout(()=>startLesson(score>=2?2:1),800);};
}

function startLesson(id){if(state.currentLesson!==id)state.currentStep=0;state.currentLesson=id;save();lessonSession={selected:{},arranged:[],showTranscript:false,recording:false,recognitionText:'',audioUrl:null};navigate(`learn-${id}`);}
const steps=['เป้าหมาย','คำศัพท์','ตัวอย่าง','ฟัง','พูด','อ่านและเขียน','ทดสอบ'];
function renderLesson(id){
 const l=lessons.find(x=>x.id===id)||lessons[0], s=Math.min(state.currentStep,6); const body=stepBody(l,s);
 shell(`<section class="lesson-shell"><button class="back" data-nav="lessons">← บทเรียนทั้งหมด</button><div class="lesson-top"><div class="progress-info"><span>บทที่ ${l.id} · ${steps[s]}</span><span>${s+1} / 7</span></div><div class="bar"><i style="width:${(s+1)/7*100}%"></i></div></div><article class="card step-card">${body}<div class="step-actions"><button class="btn secondary" id="prev" ${s===0?'disabled':''}>← ย้อนกลับ</button><button class="btn primary" id="next">${s===6?'จบบทเรียน':'ไปต่อ →'}</button></div></article></section>`);
 bindStep(l,s);
}

function stepBody(l,s){
 if(s===0)return `<p class="eyebrow">บทที่ ${l.id} · ${l.minutes} นาที</p><h2>${l.icon} ${l.title}</h2><p class="step-lead">${l.subtitle}</p><div class="goal-box"><strong>🎯 เมื่อจบบทนี้ คุณจะ…</strong><br>${l.goal}</div><div class="tip-box">💚 ไม่ต้องจำทุกอย่างในครั้งเดียว ฟังและลองใช้ก่อน แล้วเราจะพากลับมาทบทวนอีกครั้ง</div>`;
 if(s===1)return `<p class="eyebrow">คำศัพท์ใหม่</p><h2>มารู้จัก ${l.words.length} คำสำคัญ</h2><p class="step-lead">แตะปุ่มเสียงเพื่อฟัง ระบบใช้เสียงสังเคราะห์จากอุปกรณ์ของคุณ</p><div class="vocab-list">${l.words.map(w=>`<div class="word-row"><div><span class="word-en">${w[0]}</span><span class="word-th">${w[1]}</span>${state.showThaiSound?`<span class="thai-sound">เสียงประมาณ: ${w[2]}</span>`:''}</div><button class="sound-btn" data-speak="${w[0]}" aria-label="ฟังคำว่า ${w[0]}">▶</button></div>`).join('')}</div>`;
 if(s===2)return `<p class="eyebrow">ประโยคตัวอย่าง</p><h2>ดูคำในประโยคจริง</h2>${l.examples.map(e=>`<div class="example"><button class="sound-btn" data-speak="${e[0]}" aria-label="ฟังประโยค">▶</button> <strong>${e[0]}</strong><p>${e[1]}</p>${state.showThaiSound?`<p class="thai-sound">เสียงประมาณ: ${e[2]}</p>`:''}</div>`).join('')}<div class="tip-box"><strong>ทำไมจึงเรียงแบบนี้?</strong><br>${l.grammar}</div>`;
 if(s===3){const p=l.practice,sel=lessonSession.selected.listen;return `<p class="eyebrow">ฝึกฟัง</p><h2>ฟังก่อน แล้วค่อยเปิดข้อความ</h2><div class="audio-panel"><button class="btn primary" id="listen">▶ ฟังประโยค</button><button class="btn ghost" id="repeat">↻ ฟังซ้ำ</button><select class="speed" id="speed" aria-label="ความเร็วเสียง"><option value=".7">ช้า 0.7×</option><option selected value="1">ปกติ 1×</option><option value="1.2">เร็ว 1.2×</option></select><button class="btn secondary" id="reveal">${lessonSession.showTranscript?'ซ่อนข้อความ':'เปิดข้อความ'}</button></div><p class="question ${lessonSession.showTranscript?'':'hidden-text'}">${p.listen}</p><p class="question">ประโยคนี้หมายถึงอะไร?</p><div class="options">${p.choices.map((x,i)=>`<button class="option ${sel===i?(i===p.answer?'correct':'wrong'):''}" data-listen-choice="${i}">${x}</button>`).join('')}</div>${sel!==undefined?`<div class="feedback ${sel===p.answer?'':'wrong'}">${sel===p.answer?'ดีมาก! คุณจับใจความได้ถูกต้อง':'ยังไม่ใช่ แต่ไม่เป็นไรนะ ลองฟังอีกครั้ง คำตอบคือ “'+p.choices[p.answer]+'”'}</div>`:''}`;}
 if(s===4)return `<p class="eyebrow">ฝึกพูด</p><h2>ฟังแล้วพูดตาม</h2><p class="step-lead">ใช้วิธี shadowing: ฟังต้นแบบ แล้วเลียนจังหวะทีละส่วน</p><div class="audio-panel"><button class="btn primary" data-speak="${l.practice.listen}">▶ ฟังต้นแบบ</button><strong>${l.practice.listen}</strong></div><div class="record-panel"><button class="record-btn ${lessonSession.recording?'recording':''}" id="record" aria-label="${lessonSession.recording?'หยุดอัดเสียง':'เริ่มอัดเสียง'}">${lessonSession.recording?'■':'●'}</button><p>${lessonSession.recording?'กำลังอัด… กดอีกครั้งเพื่อหยุด':'กดเพื่ออัดเสียง ระบบจะขอไมโครโฟนเมื่อกดเท่านั้น'}</p><p class="muted-label">เสียงอยู่ในหน่วยความจำของเบราว์เซอร์เท่านั้น ไม่ถูกส่งออกจากอุปกรณ์</p>${lessonSession.audioUrl?`<audio controls src="${lessonSession.audioUrl}"></audio><button class="btn danger" id="deleteAudio">ลบเสียง</button>`:''}${lessonSession.recognitionText?`<div class="tip-box">ระบบได้ยิน: <b>${esc(lessonSession.recognitionText)}</b><br><small>ใช้เพื่อเทียบคำเท่านั้น ไม่ใช่คะแนนความถูกต้องของการออกเสียง</small></div>`:''}</div>`;
 if(s===5){const p=l.practice,readSel=lessonSession.selected.read;return `<p class="eyebrow">อ่านและเขียน</p><h2>อ่านเรื่องสั้น แล้วลองเขียน</h2><div class="example"><p>${p.read}</p></div><p class="question">${p.question}</p><div class="options">${p.readChoices.map((x,i)=>`<button class="option ${readSel===i?(i===p.readAnswer?'correct':'wrong'):''}" data-read-choice="${i}">${x}</button>`).join('')}</div><p class="question">เขียนต่อจากคำเริ่มต้น (ตอบได้หลายแบบ)</p><label for="writing">${p.write} …</label><input class="text-input" id="writing" placeholder="พิมพ์ประโยคภาษาอังกฤษ" value="${esc(lessonSession.selected.writing||'')}"><div id="writeFeedback"></div><button class="btn secondary" id="checkWrite">ตรวจโครงสร้างเบื้องต้น</button><div class="notice" style="margin-top:16px">แบบฝึกคำตอบอิสระตรวจได้เพียงโครงสร้างพื้นฐาน ยังไม่สามารถตัดสินความเป็นธรรมชาติหรือความถูกต้องได้ทุกแบบ</div>`;}
 const p=l.practice;return `<p class="eyebrow">ทดสอบท้ายบท</p><h2>เรียงคำให้เป็นประโยค</h2><p class="step-lead">แตะคำตามลำดับ คุณแก้ใหม่ได้เสมอ</p><div class="answer-line">${lessonSession.arranged.map((x,i)=>`<button class="word-chip" data-remove-word="${i}">${x}</button>`).join('')}</div><div class="word-bank">${p.arrange.map((x,i)=>lessonSession.arranged.includes(x)?'':`<button class="word-chip" data-word="${i}">${x}</button>`).join('')}</div><button class="btn secondary" id="checkArrange">ตรวจคำตอบ</button><div id="arrangeFeedback"></div><p class="question">เติมคำที่ได้ยิน</p><button class="sound-btn" data-speak="${p.fill[0]}${p.blank}${p.fill[1]}">▶</button> ${p.fill[0]} <input class="text-input" id="fill" style="width:150px;display:inline-block" aria-label="คำที่หายไป"> ${p.fill[1]}<button class="btn secondary" id="checkFill">ตรวจคำตอบ</button><div id="fillFeedback"></div>`;
}

let recorder, chunks=[];
function bindStep(l,s){
 document.querySelector('#prev').onclick=()=>{state.currentStep=Math.max(0,s-1);save();renderLesson(l.id);};
 document.querySelector('#next').onclick=()=>{ if(s===6)return completeLesson(l);state.currentStep=s+1;save();renderLesson(l.id);scrollTo(0,0);};
 if(s===3){const play=()=>speak(l.practice.listen,+document.querySelector('#speed').value);document.querySelector('#listen').onclick=play;document.querySelector('#repeat').onclick=play;document.querySelector('#reveal').onclick=()=>{lessonSession.showTranscript=!lessonSession.showTranscript;renderLesson(l.id)};document.querySelectorAll('[data-listen-choice]').forEach(b=>b.onclick=()=>{lessonSession.selected.listen=+b.dataset.listenChoice;if(+b.dataset.listenChoice!==l.practice.answer)addMistake(l.id,'ฟัง');else bump('ฟัง');renderLesson(l.id);});}
 if(s===4){document.querySelector('#record').onclick=()=>toggleRecord(l);const del=document.querySelector('#deleteAudio');if(del)del.onclick=()=>{URL.revokeObjectURL(lessonSession.audioUrl);lessonSession.audioUrl=null;renderLesson(l.id);};}
 if(s===5){document.querySelectorAll('[data-read-choice]').forEach(b=>b.onclick=()=>{lessonSession.selected.read=+b.dataset.readChoice;if(+b.dataset.readChoice!==l.practice.readAnswer)addMistake(l.id,'อ่าน');else bump('อ่าน');renderLesson(l.id);});document.querySelector('#checkWrite').onclick=()=>checkWriting(l);}
 if(s===6){document.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{lessonSession.arranged.push(l.practice.arrange[+b.dataset.word]);renderLesson(l.id)});document.querySelectorAll('[data-remove-word]').forEach(b=>b.onclick=()=>{lessonSession.arranged.splice(+b.dataset.removeWord,1);renderLesson(l.id)});document.querySelector('#checkArrange').onclick=()=>{const ok=lessonSession.arranged.join(' ')===l.practice.arranged;feedback('arrangeFeedback',ok,ok?'เรียงถูกแล้ว! ประธานมาก่อน ตามด้วยกริยาและข้อมูลเพิ่มเติม':'ลองดูอีกครั้งนะ ประโยคที่ถูกคือ “'+l.practice.arranged+'”');if(ok)bump('เขียน');else addMistake(l.id,'เรียงคำ');};document.querySelector('#checkFill').onclick=()=>{const ok=document.querySelector('#fill').value.trim().toLowerCase()===l.practice.blank.toLowerCase();feedback('fillFeedback',ok,ok?'ถูกต้อง! คุณฟังคำสำคัญได้แล้ว':'คำที่ได้ยินคือ “'+l.practice.blank+'” ลองฟังและพูดตามอีกครั้งนะ');if(ok)bump('ฟัง');else addMistake(l.id,'เติมคำ');};}
}
function feedback(id,ok,text){document.querySelector('#'+id).innerHTML=`<div class="feedback ${ok?'':'wrong'}">${text}</div>`;}
function addMistake(lesson,type){if(!state.mistakes.some(x=>x.lesson===lesson&&x.type===type))state.mistakes.push({lesson,type});save();}
function bump(type){state.skill[type]=Math.min(100,state.skill[type]+10);state.xp++;save();}
function checkWriting(l){const val=document.querySelector('#writing').value.trim();lessonSession.selected.writing=val;let msg,ok=false;if(!val){msg='ลองเติมประโยคสั้น ๆ ก่อนนะ';}else if(val.split(/\s+/).length<3){msg='ประโยคนี้ยังสั้นมาก ลองเพิ่มกริยาหรือข้อมูล เช่น “'+l.examples[0][0]+'”';}else{ok=true;msg='โครงสร้างเบื้องต้นดูดี! คำตอบอิสระมีได้หลายแบบ ลองอ่านออกเสียงอีกครั้ง';bump('เขียน');}feedback('writeFeedback',ok,msg);}
async function toggleRecord(l){
 if(lessonSession.recording){recorder?.stop();lessonSession.recording=false;return;}
 if(!navigator.mediaDevices?.getUserMedia){toast('เบราว์เซอร์นี้ไม่รองรับการอัดเสียง');return;}
 try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{lessonSession.audioUrl=URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType}));stream.getTracks().forEach(t=>t.stop());bump('พูด');renderLesson(l.id);};recorder.start();lessonSession.recording=true;startRecognition();renderLesson(l.id);}catch{toast('ไม่สามารถใช้ไมโครโฟนได้ คุณยังฟังและพูดตามได้โดยไม่อัดเสียง');}
}
function startRecognition(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return;const rec=new R();rec.lang='en-US';rec.interimResults=false;rec.onresult=e=>lessonSession.recognitionText=e.results[0][0].transcript;rec.onerror=()=>{};rec.start();}
function completeLesson(l){if(!state.completed.includes(l.id))state.completed.push(l.id);l.words.forEach(w=>{if(!state.learnedWords.some(x=>x[0]===w[0]))state.learnedWords.push(w)});state.mistakes=state.mistakes.filter(x=>x.lesson!==l.id);state.currentLesson=Math.min(10,l.id+1);state.currentStep=0;save();shell(`<section class="lesson-shell"><article class="card step-card review-score"><div class="trophy">🎉</div><p class="eyebrow">จบบทที่ ${l.id} แล้ว</p><h2>เก่งมาก! วันนี้คุณทำได้อีกหนึ่งก้าว</h2><p class="step-lead">ไม่จำเป็นต้องสมบูรณ์แบบ ทุกครั้งที่กลับมาทบทวน คุณจะเข้าใจชัดขึ้น</p><ul class="summary-list"><li>✓ รู้จักคำศัพท์ใหม่ ${l.words.length} คำ</li><li>✓ ฟังและพูดตามประโยคต้นแบบ</li><li>✓ อ่าน เขียน และทดสอบท้ายบท</li></ul><div class="actions" style="justify-content:center"><button class="btn secondary" data-nav="progress">ดูความก้าวหน้า</button>${l.id<10?`<button class="btn primary" data-lesson="${l.id+1}">ไปบทถัดไป →</button>`:`<button class="btn primary" data-nav="today">กลับหน้าวันนี้</button>`}</div></article></section>`);}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='english-with-yuri-data.json';a.click();URL.revokeObjectURL(a.href);}
function importData(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result);state={...structuredClone(blankState),...parsed};save();renderProgress();toast('นำเข้าข้อมูลสำเร็จ');}catch{toast('ไฟล์ข้อมูลไม่ถูกต้อง');}};reader.readAsText(file);}
function resetData(){if(confirm('ลบความก้าวหน้า คำศัพท์ และคำตอบทั้งหมดในอุปกรณ์นี้ใช่ไหม?')){localStorage.removeItem(STORAGE_KEY);state=structuredClone(blankState);renderProgress();toast('รีเซ็ตข้อมูลแล้ว');}}
window.addEventListener('hashchange',()=>{page=location.hash.slice(1)||'today';render();});
render();
